#!/usr/bin/env bash
# Print production env blocks for Vercel + Render (Firebase umkm-hub-2b955).
# Usage: scripts/print-production-env.sh [VERCEL_URL] [API_URL]
#
# Examples:
#   scripts/print-production-env.sh
#   scripts/print-production-env.sh https://umkm-hub-web.vercel.app https://umkm-hub-api.onrender.com
set -euo pipefail

VERCEL_URL="${1:-https://umkm-hub-web.vercel.app}"
API_HOST="${2:-https://umkm-hub-api.onrender.com}"
API_URL="${API_HOST%/}/api/v1"
VERCEL_HOST="${VERCEL_URL#https://}"
VERCEL_HOST="${VERCEL_HOST#http://}"
VERCEL_HOST="${VERCEL_HOST%/}"

cat <<EOF
═══════════════════════════════════════════════════════════════
  UMKM Hub production env — Firebase umkm-hub-2b955
═══════════════════════════════════════════════════════════════

── Vercel (apps/web) ── https://vercel.com/rifqimtjahyono-3455s-projects
Root Directory: apps/web

NEXT_PUBLIC_API_URL=${API_URL}
NEXT_PUBLIC_FIREBASE_API_KEY=<from Firebase console>
NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=umkm-hub-2b955.firebaseapp.com
NEXT_PUBLIC_FIREBASE_PROJECT_ID=umkm-hub-2b955
NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=umkm-hub-2b955.firebasestorage.app
NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=<from Firebase console>
NEXT_PUBLIC_FIREBASE_APP_ID=<from Firebase console>

Firebase console (web app config):
  https://console.firebase.google.com/project/umkm-hub-2b955/settings/general

── Render API (or Railway) ──
CORS_ORIGIN=${VERCEL_URL},http://localhost:3000
APP_PUBLIC_URL=${VERCEL_URL}
FIREBASE_PROJECT_ID=umkm-hub-2b955
FIREBASE_SERVICE_ACCOUNT_JSON=<paste service account JSON one line>
UPSTASH_REDIS_REST_URL=<from upstash.com>
UPSTASH_REDIS_REST_TOKEN=<from upstash.com>
DATABASE_URL=<from Render Postgres attachment>
JWT_ACCESS_SECRET=<auto-generated on Render or set manually>
JWT_REFRESH_SECRET=<auto-generated on Render or set manually>

── Firebase authorized domain (add after Vercel deploy) ──
  ${VERCEL_HOST}

── Firebase email template action URLs ──
  Verification: ${VERCEL_URL}/verify-email
  Password reset: ${VERCEL_URL}/reset-password

── Verify ──
  curl -s ${API_URL}/health
  curl -s -X POST ${API_URL}/auth/config

── Deploy commands ──
  cd apps/web && npx vercel link && npx vercel --prod
  # API: connect GitHub repo to Render and apply render.yaml
    https://dashboard.render.com/select-repo?type=blueprint

EOF
